config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  resources :notes
  resources :companies
  resources :contacts
  root 'contacts#index'
  

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    belongs_to :company
    has_many :notes
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :contact
  has_attached_file :avatar, 
  styles: { medium: "300x300>", thumb: "100x100>" }, 
  default_url: "/images/:style/missing.png"
  
    validates_attachment :avatar,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "application/pdf" ] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
     @contacts = @company.contacts
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:full_name, :short_name, :contact_phone, :website)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    #@contacts = Contact.all
    
     @q = Contact.ransack(params[:q])
    if !params.has_key?( :q)
       @contacts = Contact.all
    else
      #raise params.inspect
      @contacts = @q.result
      #@contacts = @q.result.includes(:first_name_cont, :last_name, :email)
     end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @notes = @contact.notes
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :first_name_cn, :last_name_cn, :gender, :email, :phone, :website, :company_id, :remark)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :remark, :avatar, :contact_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% content_for :title, "Editing Company" %>
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<% content_for :title, "Listing Companies" %>

<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Short name</th>
      <th>Contact phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.full_name %></td>
        <td><%= company.short_name %></td>
        <td><%= company.contact_phone %></td>
        <td><%= company.website %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path , class: "btn btn-default"  %>

app/views/companies/new.html.erb
<% content_for :title, "New Company" %>
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<% content_for :title, "Show Company" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @company.full_name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @company.short_name %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @company.contact_phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>
<h2>Contacts</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>First name </th>
      <th>Last name</th>
      <th>First name cn</th>
      <th>Last name cn</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Company</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.first_name_cn %></td>
        <td><%= contact.last_name_cn %></td>
        <td><%= contact.gender %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.website %></td>
        <td><%= contact.company_id %></td>
        <td><%= contact.remark %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Contact', new_contact_path , class: "btn btn-default" %><br/>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name_cn %><br>
    <%= f.text_field :first_name_cn %>
  </div>
  <div class="field">
    <%= f.label :last_name_cn %><br>
    <%= f.text_field :last_name_cn %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  
  <div class="field">
    <%= f.label :company_id %><br>
    <%= collection_select(:contact, :company_id, Company.all, :id, :full_name) %>
  </div>
  
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <div class="actions">
    <%= f.submit  class: "btn btn-default" %>
  </div>
<% end %>

app/views/contacts/_search_form_for.html.erb
<%= search_form_for @q do |f| %>
  <div class="row">
    <%= f.label :first_name_cont  ,class: "col-md-2"%>
    <%= f.search_field :first_name_cont , class: "col-md-2"%>
  </div>
  <div class="row">
    <%= f.label :last_name_cont  ,class: "col-md-2"%>
    <%= f.search_field :last_name_cont , class: "col-md-2"%>
   </div>
  <div class="row">
  <%= f.label :email_cont ,class: "col-md-2"%>
  <%= f.search_field :email_cont , class: "col-md-2"%>
  </div>
  <div class="row">
  <%= f.submit "search", class: "col-md-offset-2 col-md-2 btn btn-default" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing Contact" %>
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<% content_for :title, "Listing Contacts" %>
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>
<%= render 'search_form_for' %>





<table class="table table-hover">
  <thead>
    <tr>
       <%= content_tag :th, sort_link(@q, :first_name) %>
      <%= content_tag :th, sort_link(@q, :last_name) %>
      <th>First name cn</th>
      <th>Last name cn</th>
     <%= content_tag :th, sort_link(@q, :gender) %>
      <%= content_tag :th, sort_link(@q, :email) %>
      <th>Phone</th>
      <th>Website</th>
      <th>Company</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.first_name_cn %></td>
        <td><%= contact.last_name_cn %></td>
        <td><%= contact.gender %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.website %></td>
        <td><%= contact.company_id %></td>
        <td><%= contact.remark %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path , class: "btn btn-default" %>

app/views/contacts/new.html.erb
<% content_for :title, "New Contact" %>
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<% content_for :title, "Show Contact" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>First name cn:</strong>
  <%= @contact.first_name_cn %>
</p>

<p>
  <strong>Last name cn:</strong>
  <%= @contact.last_name_cn %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @contact.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @contact.website %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company_id %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @contact.remark %>
</p>

<h2>Notes</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Contact</th>
      <th>Remark</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= note.contact_id %></td>
        <td><%= note.remark %></td>
        <td><%= link_to "Download",  note.avatar.url(:original, false), target: '_blank' %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Note', new_note_path , class: "btn btn-default"%><br/>
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRM <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
        <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">CRM</a>
          </div>
          
          <% if  user_signed_in? %>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :DELETE) %>        
              </li>
            </ul>
            
            <ul class="nav navbar-nav">
              <li ><a href="/">Contacts</a></li>
              <li><a href="/companies">Companies</a></li>
              <li><a href="/notes">Notes</a></li>
            </ul>
          </div><!--/.nav-collapse -->
          

            <% else %>
              <ul class="nav navbar-nav">
                <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
              </ul>
            <% end %>
        </div><!--/.container-fluid -->
      </nav>
  <div class="panel panel-primary">
    <div class="panel-heading"> <h2 class="panel-title">Customer Relationship Management  System</h2> </div>
  <div class="panel-body">
   <%= yield %>
  </div>
  <div class="panel-footer">©2016</div>
</div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= collection_select(:note, :contact_id, Contact.all, :id, :first_name) %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<% content_for :title, "Editing Note" %>
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<% content_for :title, "Listing Notes" %>
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Contact</th>
      <th>Remark</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= note.contact_id %></td>
        <td><%= note.remark %></td>
        <td><%= link_to "Download",  note.avatar.url(:original, false), target: '_blank' %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path , class: "btn btn-default"%>

app/views/notes/new.html.erb
<% content_for :title, "New Note" %>
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<% content_for :title, "Show Note" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>
<p>
  <strong>contact:</strong>
  <%= @note.contact_id %>
</p>
<p>
  <strong>Remark:</strong>
  <%= @note.remark %>
</p>

<p>
  <strong>Avatar:</strong>

  <%= link_to "Download",  @note.avatar.url(:original, false), target: '_blank' %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>